# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.2.0
      #      - image: circleci/openjdk:8-jdk-stretch
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    # environment:
    # JAVA_HOME:  /usr/lib/jvm/java-8-openjdk-amd64

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install dependencies"
          command: |
            npm install
      - run: npm install jest-junit #just for CircleCI

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Start Vegetable API"
          command: npm start
          background: true

      - run:
          name: "Run tests"
          command: |
            npm test -- --runInBand --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/

      - store_test_results:
          path: ./reports/junit

      - store_artifacts:
          path: ./reports/junit
